[package]
name = "arborio"
version = "0.1.0"
authors = ["Audrey Dutcher <audrey@rhelmot.io>", "Skye Jensen <me@skye.cat>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arborio-derive = { version = "*", path = "../arborio-derive" }
array-init = "^2.0"
byteorder = "^1.4"
celeste = "^2"
confy = "^0.4"
fltk = "^1.0"
itertools = "^0.10"
lazy_static = "^1.4"
num = "^0.4.0"
nom = "^7.0"
rand = "^0.8"
serde = { version = "^1.0", features = ["derive" ] }
serde-xml-rs = "^0.4"
serde_yaml = "^0.8"
include_dir = "^0.6"
