[package]
name = "arborio"
version = "0.1.0"
authors = ["Audrey Dutcher <audrey@rhelmot.io>", "Skye Jensen <me@skye.cat>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "^2.0"
celeste = "^2"
rand = "^0.8"
byteorder = "^1.4"
serde = { version = "^1.0", features = ["derive" ] }
serde-xml-rs = "^0.4"
confy = "^0.4"
lazy_static = "^1.4"
serde_yaml = "^0.8"
nom = "^6.2"
include_dir = "^0.6"
vizia = { path = "../../rust/VIZIA" }
#femtovg = {git = "https://github.com/femtovg/femtovg", rev = "138a45d7b92419cc9eb2566acef7fadf25b81c00", default-features = false} # not really a dependency, since vizia depends on it
femtovg = {path = "../../rust/femtovg", default-features = false}
imgref = "^1.9"  # not really a dependency either
rgb = "^0.8"  # not really a dependency either
dialog = "^0.3"
euclid = "^0.22"
Inflector = "^0.11"
itertools = "^0.10"
enum-iterator = "^0.7"
num-traits = "^0.2" # not really a dependency either
