[package]
name = "arborio"
version = "0.1.0"
authors = ["Audrey Dutcher <audrey@rhelmot.io>", "Skye Jensen <me@skye-c.at>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arborio-derive = { path = "./derive" }
array-init = "^2.0"
celeste = "^2"
byteorder = "^1.4"
serde = { version = "^1.0", features = ["derive" ] }
serde-xml-rs = "^0.5"
confy = "^0.4"
lazy_static = "^1.4"
serde_yaml = "^0.8"
nom = "^7.1"
include_dir = "^0.7"
#vizia = { path = "../../rust/VIZIA" }
vizia = {git = "https://github.com/rhelmot/VIZIA", rev = "9ff282289e10c407d4a3e6b6b4deb40319594c43" }
femtovg = { version = "0.3.0", default-features = false, features = ["image-loading"] } # inhert from vizia
image = { version = "0.24.0", default-features = false, features = ["png"] } # inherit from femtovg
imgref = "1.6.1"  # inherit from femtovg
rgb = "0.8.20"  # inherit from femtovg
dialog = "^0.3"
euclid = "^0.22"
Inflector = "^0.11"
itertools = "^0.10"
enum-iterator = "^0.7"
num-traits = "0.2.10" # inherit from euclid
walkdir = "^2"
zip = "^0.5"
elsa = "^1.6"
lru = "^0.7"
enum_dispatch = "^0.3"
#stable_deref_trait = "^1.2"
parking_lot = "^0.12"

[profile.dev.package.vizia_core]
opt-level = 2
[profile.dev.package.femtovg]
opt-level = 2
