name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      RUSTFLAGS: '-D warnings'
    steps:
    - uses: actions/checkout@v2
#    - name: Install XCB and GL dependencies
#      run: |
#        sudo apt update
#        # baseview dependencies
#        sudo apt install libx11-xcb-dev libxcb-dri2-0-dev libgl1-mesa-dev libxcb-icccm4-dev libxcursor-dev libxcb-{render,shape,xfixes}0-dev
#      if: contains(matrix.os, 'ubuntu')
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Check Format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Clippy Lint
      run: cargo clippy
    - name: Run Tests
      run: cargo test --verbose
